### ISSUE TITLE
Paquete NuGet no tiene dependencia con RestSharp

### ISSUE THREAD

**Issue by R2D221** [bscheiman/Conekta#8]
Instalando el paquete NuGet, todo parece ir bien, pero al momento de intentar cobrar, lanza una excepción que no encuentra el paquete de RestSharp.

**Comment by bscheiman** [comment]
Sobre que plataforma estas probando? Voy a ver si lo puedo replicar

**Comment by R2D221** [comment]
Visual Studio 2015, Windows 10, en una aplicación ASP.NET MVC.

**Comment by bscheiman** [comment]
MVC 5?

**Comment by R2D221** [comment]
Sí

**Comment by bscheiman** [comment]
Arreglado, gracias. Estoy subiendo v2.1.1449592878 a NuGet; dale unos 15m para que aparezca.
