### ISSUE TITLE
ChargeAsync ignora los lineItems

### ISSUE THREAD

**Issue by R2D221** [bscheiman/Conekta#9]
Agregando los lineItems a ChargeAsync regresa una respuesta de error indicando que los lineItems no están.

Revisando el código, creo que encontré la razón:

https://github.com/bscheiman/Conekta/blob/master/Conekta.NET45/ConektaLib.cs#L96

Se crea finalLineItems:

```
var finalLineItems = new List<Dictionary<string, object>>();
```

Pero nunca se agrega nada, y después:

```
details["line_items"] = finalLineItems;
```

Se agrega la lista vacía a los detalles.

**Comment by bscheiman** [comment]
Buen ojo, ReSharper justo me lo acababa de reportar. Fix OTW

**Comment by bscheiman** [comment]
NuGet v2.1.1449593700
